version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /tmp/registry-dev
http:
    addr: :5000
    secret: asecretforlocaldevelopment
    debug:
        addr: localhost:5001

auth:
  token:
    realm: https://garant.dev.docker.com/token
    service: registry.dev.docker.com
    issuer: garant.dev.docker.com
    rootcertbundle: cmd/registry/token_roots.pem

notifications:
    endpoints:
        - name: local-devhub
          url: https://registry-hub.dev.docker.com/distribution_hooks/v1/
          headers:
             Authorization: [AuthToken testnotificationtoken]
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: false
